package com.speedystone.greendaodemo.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.idol.idolnews.bean.TopStoriesEntity;
import com.idol.idolnews.SQLite.User;

import com.speedystone.greendaodemo.db.TopStoriesEntityDao;
import com.speedystone.greendaodemo.db.UserDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig topStoriesEntityDaoConfig;
    private final DaoConfig userDaoConfig;

    private final TopStoriesEntityDao topStoriesEntityDao;
    private final UserDao userDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        topStoriesEntityDaoConfig = daoConfigMap.get(TopStoriesEntityDao.class).clone();
        topStoriesEntityDaoConfig.initIdentityScope(type);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        topStoriesEntityDao = new TopStoriesEntityDao(topStoriesEntityDaoConfig, this);
        userDao = new UserDao(userDaoConfig, this);

        registerDao(TopStoriesEntity.class, topStoriesEntityDao);
        registerDao(User.class, userDao);
    }
    
    public void clear() {
        topStoriesEntityDaoConfig.clearIdentityScope();
        userDaoConfig.clearIdentityScope();
    }

    public TopStoriesEntityDao getTopStoriesEntityDao() {
        return topStoriesEntityDao;
    }

    public UserDao getUserDao() {
        return userDao;
    }

}
